version: '3.7'

services:
  mysql:
    container_name: app_mysql
    restart: always
    platform: linux/x86_64
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
      - MYSQL_DATABASE=app_docker
    ports:
      - '3306:3306'
    volumes:
      - app_mysql_docker:/var/lib/mysql

volumes:
  app_mysql_docker:
